CREATE DATABASE Mogumogu;
USE Mogumogu;

CREATE TABLE meals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meal_name VARCHAR(100) NOT NULL,
  meal_type VARCHAR(50) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  health INT DEFAULT 100,
  streak INT DEFAULT 0,
  last_fed DATE
);